name: Snake Crawler

# Controls when the workflow will run
on:
  # Runs every day at 06 am
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '00 06 * * *'
jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/snake.svg
          palette: "ffcc00" 
      
      - name: Commit files
        run: |
          git config user.email "mandeepdhakal11@gmail.com"
          git config user.name "mandeep111"
          git add .
          git commit -m "update readme: snake crawler" --allow-empty
      
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.Snake_Crawler }}
          branch: ${{ github.ref }}
