name: Snake Crawler

# Controls when the workflow will run
on:
  # Runs every day at 06 am
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '00 06 * * *'

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Generate Snake
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
            dist/dark.svg?palette=github-dark&color_snake=blue
            dist/light.svg?color_snake=#7845ab
            dist/ocean.gif?color_snake=blue&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: devcard
        uses: dailydotdev/action-devcard@2.0.2
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}

      - name: Commit files
        run: |
          git config --global user.email "mandeepdhakal11@gmail.com"
          git config --global user.name "mandeep111"
          git add .
          git commit -m "update readme: snake crawler" --allow-empty
          git pull --no-rebase origin main
      
      - name: Push
        run: |
          git push origin main
