name: Snake Crawler

# Controls when the workflow will run
on:
  # Runs every day at 06 am
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '00 06 * * *'
jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
      
      - name: devcard
        uses: dailydotdev/action-devcard@2.0.2
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}

      - name: Commit files
        run: |
          git config --global user.email "mandeepdhakal11@gmail.com"
          git config --global user.name "mandeep111"
          git add .
          git commit -m "update readme: snake crawler" --allow-empty
      
      - name: Push
        run: git push origin main

